### ISSUE TITLE
report name instead of value when using DNS A record

### ISSUE THREAD

**Issue by vincentcox** [jimen0/fdns#4]
Is there a way this tool can fetch all subdomains? In the example it returns all IP's, but I am really interested in all the subdomains.

Thanks in advance!

**Comment by jimen0** [comment]
Hi!

I don't plan to change the project to report subdomains instead of IP addresses. But you can do one of the following actions to get subdomains instead of IPs:

1. Use the `CNAME` record instead of `A`, it will [report subdomains](https://github.com/jimen0/fdns/blob/7b884ba5c8b183c84d3ab0ec09e3b7350053687d/fdns.go#L34) instead of where they point to.
2. Fork the project and replace [this line](https://github.com/jimen0/fdns/blob/7b884ba5c8b183c84d3ab0ec09e3b7350053687d/fdns.go#L26) with the following:
     ```go
    return e.Name, nil
     ```

Hope this answers your question.

Kind regards

**Comment by vincentcox** [comment]
Thanks for your answer! I can fork this indeed and implement your suggestion. Would this GO implementation be faster than `pigz -dc filename.json.gz | grep 'yahoo.com' |  jq '.name' `?

**Comment by jimen0** [comment]
Hi.

No. It won't be faster. It will be >4x slower indeed. My version parses all JSON entries, the one you posted only parses the JSON entries where the substring `yahoo.com` appears.

Kind regards

**Comment by vincentcox** [comment]
Allright, thanks for the information! Have a nice weekend.

**Comment by vincentcox** [comment]
Do you have an idea what goes wrong when I want to install it?
```
vincent@usbstick:~/src/github.com/jimen0/fdns$ go build cmd/fdns
can't load package: package cmd/fdns: cannot find package "." in:
	/home/vincent/go/src/cmd/fdns

```

**Comment by jimen0** [comment]
Hi.

Sorry, I forgot to update the documentation. Use this or just add `.go` after `cmd/fdns` in your command.

```sh
go get -u github.com/jimen0/fdns
cd $GOPATH/src/github.com/jimen0/fdns
go build cmd/fdns.go
```

Kind regards
