### ISSUE TITLE
proposal: allow wildcard searches

### ISSUE THREAD

**Issue by uBadRequest** [jimen0/fdns#8]
I'm looking to be able to find all the domains that contain a specific keyword, would you be able to add a flag for wildcard and returning just the top domain?

**Comment by jimen0** [comment]
Hi @uBadRequest,

Thanks for your proposal. Could you please detail it a bit more? Currently, `fdns` accepts a set of domains it looks for. Its main use case is to be used as a library and not as a CLI tool, so I'm not sure if your proposal fits my project's goal, but I want to know more about it before declining it or implementing it.

Would you like to be able to support arbitrary strings instead of full domains in the parser? See:
https://github.com/jimen0/fdns/blob/346db7261c80b83adac94e0ecab624a2a9726066/fdns.go#L92-L100

So, instead of complete domains and querying for entries with that suffixes, just plain strings and querying for entries that contain them, right?

Just for your information, they would have to be raw strings, I'm not planning to add support for regular expressions by any means.

Thanks,
